name: Dev - Unit Test

on:
  workflow_dispatch:

jobs:
  job1:
    name: Run Unit Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set environment variable
      run: echo "DEV_TEST=true" >> $GITHUB_ENV

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1

    - name: Compile with Gradle
      run: gradle compileJava -i

    - name: Unit Test
      run: gradle test -i

    - name: Upload test reports
      uses: actions/upload-artifact@v6
      with:
        # Using github.run_number here to reduce confusion when downloading & comparing from several builds
        name: ${{ github.run_number }}-test-reports
        path: build/reports/tests/
