name: Native Image - Snapshot

on:
  workflow_dispatch:
  workflow_call:

jobs:
  clean_release:
    name: 'Clean the snapshot-native pre-release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Clean release and tag
        run: |
          gh release delete snapshot-native --cleanup-tag -y || true
          echo "::notice title=release snapshot-native::snapshot - Native Image at ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/tag/snapshot-native"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_linux_amd64:
    name: 'Build Native Image linux-amd64'
    needs: clean_release
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v6

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          distribution: liberica
          cache: gradle

      - name: Prepare env and build GPLv2 native image
        shell: bash
        run: |
          ./gradlew :plantuml-gplv2:nativeFullCompile :plantuml-gplv2:nativeHeadlessCompile -x test

      - name: Archive Linux builds
        shell: bash
        run: |
          zip -r plantuml-full-linux-amd64-SNAPSHOT.zip plantuml-gplv2/build/native/nativeFullCompile/
          zip -r plantuml-headless-linux-amd64-SNAPSHOT.zip plantuml-gplv2/build/native/nativeHeadlessCompile/

      - name: Upload build artifacts (Linux)
        uses: actions/upload-artifact@v5
        with:
          name: linux-amd64
          path: |
            plantuml-full-linux-amd64-SNAPSHOT.zip
            plantuml-headless-linux-amd64-SNAPSHOT.zip

  build_windows_amd64:
    name: 'Build Native Image windows-amd64'
    needs: clean_release
    runs-on: windows-latest
    timeout-minutes: 90

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: liberica
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle

      - name: Force tmp dir on D for Java
        shell: pwsh
        run: |
          echo "JAVA_TOOL_OPTIONS=-Djava.io.tmpdir=$env:RUNNER_TEMP" >> $env:GITHUB_ENV

      - name: Build GPLv2 native image
        shell: pwsh
        run: ./gradlew :plantuml-gplv2:nativeFullCompile :plantuml-gplv2:nativeHeadlessCompile -x test

      - name: Archive Windows builds
        shell: pwsh
        run: |
          Compress-Archive -Path "plantuml-gplv2/build/native/nativeFullCompile/*" -DestinationPath "plantuml-full-windows-amd64-SNAPSHOT.zip"
          Compress-Archive -Path "plantuml-gplv2/build/native/nativeHeadlessCompile/*" -DestinationPath "plantuml-headless-windows-amd64-SNAPSHOT.zip"

      - name: Upload build artifacts (Windows)
        uses: actions/upload-artifact@v5
        with:
          name: windows-amd64
          path: |
            plantuml-full-windows-amd64-SNAPSHOT.zip
            plantuml-headless-windows-amd64-SNAPSHOT.zip

  build_macos_arm64:
    name: 'Build Native Image darwin-arm64'
    needs: clean_release
    runs-on: macos-latest
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v6

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          distribution: liberica
          cache: gradle

      - name: Build GPLv2 native image
        shell: bash
        run: |
          ./gradlew :plantuml-gplv2:nativeFullCompile :plantuml-gplv2:nativeHeadlessCompile -x test

      - name: Archive macOS builds
        shell: bash
        run: |
          zip -r plantuml-full-darwin-arm64-SNAPSHOT.zip plantuml-gplv2/build/native/nativeFullCompile/
          zip -r plantuml-headless-darwin-arm64-SNAPSHOT.zip plantuml-gplv2/build/native/nativeHeadlessCompile/

      - name: Upload build artifacts (macOS)
        uses: actions/upload-artifact@v5
        with:
          name: darwin-arm64
          path: |
            plantuml-full-darwin-arm64-SNAPSHOT.zip
            plantuml-headless-darwin-arm64-SNAPSHOT.zip

  publish_release:
    name: Publish combined release
    needs:
      - build_linux_amd64
      - build_windows_amd64
      - build_macos_arm64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
        
      - uses: actions/download-artifact@v7
        with:
          merge-multiple: true
          path: artifacts/

      - name: List artifacts
        run: ls -lh artifacts/

      - name: Prepare env
        shell: bash
        run: |
          VERSION=$(grep 'version =' gradle.properties | cut -d' ' -f 3)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "DATETIME=$(date -u +'%F at %T (UTC)')" >> $GITHUB_ENV
          echo "Resolved VERSION=$VERSION"

      - name: Upload all binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "artifacts/*.zip"
          file_glob: true
          tag: snapshot-native
          release_name: snapshot - Native Image (~v${{ env.VERSION }})
          overwrite: true
          make_latest: false
          prerelease: true
          body: |
            ## Version ~v${{ env.VERSION }} of the ${{ env.DATETIME }}
            This is a [Native Image](https://www.graalvm.org/latest/reference-manual/native-image/) pre-release of [the latest development work](https://github.com/plantuml/plantuml/commits/).
            ⚠️  **It is not ready for general use** ⚠️
            ⏱  _Snapshot taken the ${{ env.DATETIME }}_
