name: Native Image - Snapshot

on:
  workflow_dispatch:
  workflow_call:
#  push:
#    branches:
#      - master
#    paths-ignore:
#      - '**.md'
#      - 'docs/**'

jobs:
  clean_release:
    name: 'Clean the snapshot-native pre-release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
 
      - name: Clean release and tag
        run: |
          gh release delete snapshot-native --cleanup-tag -y || true
          echo "::notice title=release snapshot-native::snapshot - Native Image at ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/tag/snapshot-native"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_image_linux_amd64:
    name: 'Build Native Image linux-amd64'
    needs: clean_release
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          distribution: liberica
          cache: gradle

      - name: Prepare env and build GPLv2 native image
        shell: bash
        run: |
          echo "VERSION=$(grep 'version =' gradle.properties | cut -d' ' -f 3)" >> $GITHUB_ENV
          echo "DATETIME=$(date -u +'%F at %T (UTC)')" >> $GITHUB_ENV
          ./gradlew :plantuml-gplv2:nativeFullCompile :plantuml-gplv2:nativeHeadlessCompile -x test --stacktrace --info

      - name: Archive Full & Headless Releases
        shell: bash
        run: |
          zip -r "plantuml-full-linux-amd64-SNAPSHOT.zip" plantuml-gplv2/build/native/nativeFullCompile/
          zip -r "plantuml-headless-linux-amd64-SNAPSHOT.zip" plantuml-gplv2/build/native/nativeHeadlessCompile/
          ls -lh *.zip

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "plantuml-gplv2/build/native/native*/plantuml-*--SNAPSHOT.zip"
          file_glob: true
          tag: snapshot-native
          release_name: snapshot - Native Image (~v${{ env.VERSION }})
          overwrite: true
          make_latest: false
          prerelease: true
          body: |
            ## Version ~v${{ env.VERSION }} of the ${{ env.DATETIME }}
            This is a [Native Image](https://www.graalvm.org/latest/reference-manual/native-image/) pre-release of [the latest development work](https://github.com/plantuml/plantuml/commits/).
            ⚠️  **It is not ready for general use** ⚠️
            ⏱  _Snapshot taken the ${{ env.DATETIME }}_
